FROM python:3.9-slim

#set working directory
WORKDIR /app 

COPY src/consumer/requirements.txt /app/

#install dependencies from requiremnts file, update as the application grows
RUN pip install --no-cache-dir -r requirements.txt

COPY src/consumer/ /app/

CMD ["python", "consumer.py"]
